<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <CassotisVersion>2.0.0</CassotisVersion>
    <CassotisVersionQuad>2.0.0.0</CassotisVersionQuad>
    <CassotisVersionMajor>2</CassotisVersionMajor>
    <CassotisVersionMinor>0</CassotisVersionMinor>
    <CassotisVersionRelease>0</CassotisVersionRelease>
    <CassotisVersionBuild>0</CassotisVersionBuild>
  </PropertyGroup>
</Project>
